export const START_FETCHING = 'START_FETCHING';
export const FETCH_USER_DATA = 'FETCH_USER_DATA';
export const SET_USER_DATA = 'RECEIVE_USER_DATA';
export const FETCH_USER_DATA_FAILED = 'FETCH_USER_DATA_FAILED';
