export const SEARCH = 'SEARCH';
export const START_FETCHING = 'START_FETCHING';
export const SET_SEARCH_DATA = 'SET_SEARCH_DATA';
export const FETCH_SEARCH_DATA_FAILED = 'FETCH_SEARCH_DATA_FAILED';
export const CLEAR = 'CLEAR';
export const SET_USER_DATA = 'SET_USER_DATA';
